"""采集与简报配置：主题词、时间窗口、输出路径。"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
BRIEFS_DIR = ROOT / "briefs"
LOGS_DIR = ROOT / "logs"
LIBRARY_DIR = BRIEFS_DIR / "library"

# 默认回看天数（覆盖时区差，避免漏掉“昨天深夜”发布的内容）
LOOKBACK_DAYS = 3
MAX_ITEMS_PER_SOURCE = 40
CRAWL_TIMEOUT_MS = 90_000
CRAWL_DELAY_SEC = 2.0
CONCURRENCY = 3
DAILY_RUN_AT = "12:10"
DIGEST_THEME_LIMIT = 8
# 0 表示不按“文章条数”截断；简报按主题合并，空稿不入报
DIGEST_STORY_LIMIT = 0
SKIP_TITLE_KEYWORDS = [
    "decommissioning",
    "roman ship replica",
    "cruise ship",
    "cruise liner",
    "yacht",
    "superyacht",
    "job listing",
    "we are hiring",
]

# 石油运输：油轮船型、运价、船燃、原油流向、关键水道
OIL_TRANSPORT_KEYWORDS = [
    "oil",
    "crude",
    "petroleum",
    "tanker",
    "tankers",
    "vlcc",
    "ulcc",
    "suezmax",
    "aframax",
    "lr1",
    "lr2",
    "mr tanker",
    "product tanker",
    "chemical tanker",
    "chem tanker",
    "oil tanker",
    "vlgc",
    "lpg",
    "oil cargo",
    "oil export",
    "oil import",
    "oil trade",
    "oil shipment",
    "oil freight",
    "tanker rate",
    "spot rate",
    "time charter",
    "time-charter",
    "ipo",
    "oslo bors",
    "oslo stock",
    "tce",
    "worldscale",
    "freight rate",
    "tanker earnings",
    "fixture",
    "bunker",
    "bunkering",
    "marine fuel",
    "fuel oil",
    "vlsfo",
    "naphtha",
    "condensate",
    "crude oil",
    "petroleum product",
    "oil terminal",
    "oil port",
    "demurrage",
    "brent",
    "wti",
    "opec",
    "pdvsa",
    "hormuz",
    "strait of hormuz",
    "persian gulf",
    "arabian gulf",
    "middle east gulf",
    "kharg",
    "yanbu",
    "ras tanura",
    "ain sukhna",
    "sidi kerir",
    "ceyhan",
    "black sea",
    "red sea",
    "bab el-mandeb",
    "bab el mandeb",
    "gulf of aden",
    "suez canal",
    "price cap",
    "oil price cap",
    "g7 price cap",
    "shadow fleet",
    "dark fleet",
    "ghost fleet",
    "sts transfer",
    "ship-to-ship",
    "oil loading",
    "oil discharge",
    "crude export",
    "transit fee",
    "frontline",
    "euronav",
    "odfjell",
    "dht",
    "piracy",
    "pirate",
    "hijack",
    "hijacked",
    "somalia",
    "石油",
    "原油",
    "油轮",
    "成品油",
    "燃油",
    "船用燃料",
    "加注",
    "即期运价",
    "运价",
    "租约",
    "滞期",
    "化学品船",
    "超大型原油",
    "石油运输",
    "原油运输",
    "霍尔木兹",
    "波斯湾",
    "红海",
    "黑海",
    "亚丁湾",
    "海盗",
    "劫持",
    "布伦特",
    "欧佩克",
    "过境费",
]

# 经济制裁：名单、船旗、二级制裁、执法与规避
SANCTIONS_KEYWORDS = [
    "sanction",
    "sanctions",
    "sanctioned",
    "ofac",
    "ofsi",
    "embargo",
    "sdn",
    "designat",
    "restrictive measure",
    "cfsp",
    "833/2014",
    "2014/145",
    "2014/512",
    "russia package",
    "secondary sanction",
    "secondary sanctions",
    "export control",
    "asset freeze",
    "blocked person",
    "general license",
    "false flag",
    "sanctions evasion",
    "economic d-day",
    "outcast",
    "ship registr",
    "ship registry",
    "ship registries",
    "flag state",
    "flag of convenience",
    "blacklist",
    "blacklisted",
    "blockade",
    "price cap",
    "制裁",
    "受制裁",
    "禁运",
    "制裁名单",
    "二级制裁",
    "船旗",
    "假旗",
    "经济d日",
]

# 与石油制裁高度相关的辖区/对象
FOCUS_KEYWORDS = [
    "iran",
    "iranian",
    "russia",
    "russian",
    "venezuela",
    "syria",
    "syrian",
    "ukraine",
    "ukrainian",
    "iraq",
    "iraqi",
    "saudi",
    "houthi",
    "yemen",
    "somalia",
    "tanker",
    "vlcc",
    "energy",
    "oil",
    "crude",
    "petroleum",
    "shadow fleet",
    "dark fleet",
    "price cap",
    "hormuz",
    "伊朗",
    "俄罗斯",
    "委内瑞拉",
    "叙利亚",
    "乌克兰",
    "伊拉克",
    "沙特",
    "胡塞",
    "油轮",
]

# 第三方源：地缘热点需同时出现航运语境
GEO_KEYWORDS = [
    "iran",
    "iranian",
    "russia",
    "russian",
    "venezuela",
    "syria",
    "ukraine",
    "ukrainian",
    "iraq",
    "iraqi",
    "saudi",
    "houthi",
    "yemen",
    "somalia",
    "trump",
    "伊朗",
    "俄罗斯",
    "委内瑞拉",
    "叙利亚",
    "乌克兰",
    "伊拉克",
    "沙特",
    "胡塞",
    "索马里",
    "特朗普",
]

MARITIME_CONTEXT_KEYWORDS = [
    "ship",
    "vessel",
    "maritime",
    "tanker",
    "tankers",
    "vlcc",
    "port",
    "cargo",
    "imo",
    "fleet",
    "seafarer",
    "crew",
    "registry",
    "hijack",
    "pirate",
    "piracy",
    "charter",
    "freight",
    "bunker",
    "attack",
    "船舶",
    "港口",
    "船队",
    "海员",
    "油轮",
    "劫持",
    "海盗",
    "运价",
    "租约",
]

# 干散货/集装箱等：入选后标为「航运（非油轮）」，不再直接丢弃
NON_TANKER_SHIPPING_KEYWORDS = [
    "bulk carrier",
    "bulker",
    "capesize",
    "panamax",
    "kamsarmax",
    "ultramax",
    "containership",
    "container ship",
    "boxship",
    "liner",
    "dry bulk",
    "lng carrier",
    "lpg carrier",
    "干散货",
    "集装箱",
    "散货船",
    "箱船",
]

# 欧盟 Russia Package / 相关法规
EU_RUSSIA_KEYWORDS = [
    "russia",
    "russian",
    "ukraine",
    "restrictive measure",
    "sanction",
    "package",
    "833/2014",
    "2014/145",
    "2014/512",
    "shadow fleet",
    "energy",
    "oil",
    "tanker",
]

EURLEX_KEYWORDS = [
    "2014/145/cfsp",
    "2014/145",
    "2014/512/cfsp",
    "2014/512",
    "833/2014",
    "32014r0833",
    "32014d0145",
    "32014d0512",
    "restrictive measures",
    "russia",
]

NAV_TITLE_BLOCKLIST = {
    "home",
    "subscribe",
    "sign in",
    "log in",
    "login",
    "register",
    "contact",
    "about",
    "about us",
    "privacy",
    "privacy policy",
    "cookie",
    "cookies",
    "advertise",
    "careers",
    "jobs",
    "search",
    "newsletter",
    "follow us",
    "read more",
    "see all",
    "view all",
    "skip to content",
    "skip to main content",
}

URL_BLOCK_FRAGMENTS = [
    "/tag/",
    "/tags/",
    "/author/",
    "/authors/",
    "/wp-login",
    "/cart",
    "/account",
    "/login",
    "/signin",
    "/media/",
    "javascript:",
    "mailto:",
    "download?inline",
]

LOGIN_HINTS = [
    "sign in",
    "log in",
    "login",
    "subscribe to continue",
    "create an account",
    "paywall",
    "subscribers only",
    "buy a subscription",
]

# 微信公众号正文：本地 WeWe RSS，默认 http://127.0.0.1:4000
WECHAT_RSS_BASE = "http://127.0.0.1:4000"

# 知识库与推送
LIBRARY_JSON = "articles.json"
ALERTS_JSON = "alerts.json"
TIME_PRESETS = {
    "24h": 1,
    "week": 7,
    "month": 30,
    "year_2026": None,  # 在界面按年份筛
}

